### ISSUE TITLE
What language are the schemas going to be in?

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/spec.rebase.org#1]
Here is an example using YAML and JSON Schema:

https://w3id.org/traceability/openapi/

Feel free to use Open API Spec 3, its pretty awesome.

**Comment by bumblefudge** [comment]
The Serto team also demoed a pretty cool tool at ProdMan a few weeks back that they made for "decorating" JSON Schemata for LD-ification (inspired, perhaps by the trace-vocab tooling?).  It might be a good tool to use for wrapping JSON Schema in a mark-up layer for spitting out Contexts, should that be a goal.

https://schemas.serto.id/

**Comment by OR13** [comment]
We are using Open API 3 + JSON-LD.
